/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jonesx_videoplayer_VideoPlayer */

#ifndef _Included_jonesx_videoplayer_VideoPlayer
#define _Included_jonesx_videoplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jonesx_videoplayer_VideoPlayer
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_jonesx_videoplayer_VideoPlayer_play
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
